manager/public/index.html, manager/src/helpers/interfaces/FIlterVuln.ts, manager/src/pages/Internal/Dashboard/VulnerabilitiesDetails/index.tsx, manager/src/pages/Internal/Vulnerabilities/index.tsx, manager/src/pages/Internal/Webhooks/index.tsx, manager/src/services/core.ts, manager/src/services/vulnerabilities.ts, manager/src/services/webhook.ts
- Vulnerabilities manager integration
=> Vulnerabilities manager integration

deployments/compose/compose-dev.yaml, deployments/compose/compose.yaml, manager/src/helpers/formatters/chartData.ts, manager/src/pages/Internal/Dashboard/VulnerabilitiesByDeveloper/index.tsx, manager/src/pages/Internal/Dashboard/VulnerabilitiesByLanguage/index.tsx, manager/src/pages/Internal/Dashboard/VulnerabilitiesByRepository/index.tsx, manager/src/pages/Internal/Dashboard/VulnerabilitiesDetails/index.tsx, manager/src/pages/Internal/Dashboard/VulnerabilitiesTimeLine/index.tsx, manager/src/pages/Internal/Vulnerabilities/index.tsx, manager/src/services/vulnerabilities.ts
- Fix route do get all vulnerabilities.
- Fix update route vulnerabilities.
- Order data of charts: Developer, Repository and Timeline.
- Add menu with zoom for timeline.
=> Analytic manager improvees

manager/src/contexts/Workspace.tsx
Added rule to ignore role when set as null workspace
=> Added rule to ignore role when set as null workspace

manager/src/config/i18n/enUS.json, manager/src/config/i18n/es.json, manager/src/config/i18n/ptBR.json, manager/src/pages/Internal/Dashboard/index.tsx
=> change text i18n export

deployments/helm/horusec-platform/templates/deployments/auth.yaml
- Fix the auth.yaml
- Add manager.uri.scheme and auth.uri.scheme
- helm install horusec-platform -f deployments/helm/horusec-platform/values.yaml deployments/helm/horusec-platform -n horusec-system-test --dry-run
=> Add uri.scheme

deployments/helm/horusec-platform/templates/deployments/auth.yaml
Fix HORUSEC_MANAGER_URL and HORUSEC_AUTH_URL
`helm install horusec-platform -f deployments/helm/horusec-platform/values.yaml deployments/helm/horusec-platform -n horusec-system-test --dry-run`
=> Fix HORUSEC_MANAGER_URL and HORUSEC_AUTH_URL

api/go.mod, api/internal/entities/core/repository.go, api/internal/entities/core/workspace.go, api/internal/enums/values.go, api/internal/repositories/repository/repository.go, api/internal/repositories/repository/repository_test.go, core/internal/enums/repository/values.go, core/internal/repositories/repository/repository.go
=> Fixing error in ldap groups and heritage

core/internal/entities/token/response.go
Fixing repositoryID response when the token workspace
=> Fixing repositoryID response when the token workspace

manager/cypress/fixtures/login/horusec/wrong-password.json, manager/src/config/i18n/enUS.json, manager/src/config/i18n/es.json, manager/src/config/i18n/ptBR.json, manager/src/helpers/hooks/useResponseMessage.ts
Fix LDAP group error message, and verify all other messages.
=> LDAP group error message

core/internal/entities/workspace/workspace_response.go, core/internal/repositories/workspace/workspace.go, manager/src/components/HomeCard/index.tsx, manager/src/helpers/interfaces/Workspace.ts
Repositories count in workspace
=> Repositories count in workspace

README.md
Signed-off-by: nathanmartinszup <nathan.martins@zup.com.br>
=> Adding communication channels in readme

.github/workflows/release.yml
Merging a pull request from a `release/*` or a `hotfix/*` branch into the `main` branch will trigger an event to build and publish all docker images in parallel. After builds are completed, the GitHub release will be created.
=> The automation of release processes

manager/src/components/Select/index.tsx, manager/src/config/themes/material-ui.ts, manager/src/helpers/hooks/usePermissions.ts, manager/src/pages/Overview/Vulnerabilities/index.tsx
=> improve colors and fix components

manager/src/components/Header/index.tsx
=> add new option repositories

.semver.yaml, deployments/compose/compose.yaml, deployments/helm/horusec-platform/Chart.yaml, deployments/helm/horusec-platform/README.md, deployments/helm/horusec-platform/values.yaml
=> Release v2.16.5

manager/src/contexts/Repository.tsx, manager/src/pages/Home/Workspace/index.tsx, manager/src/pages/Overview/Vulnerabilities/index.tsx
Fixing infinite scrolling in list of repositories on home screen
=> Infinite scrolling in list of repositories on home screen

.semver.yaml, deployments/compose/compose.yaml, deployments/helm/horusec-platform/README.md, deployments/helm/horusec-platform/values.yaml, manager/package.json
Signed-off-by: nathanmartinszup <nathan.martins@zup.com.br>
=> Updating platform version

renovate.json
=> make develop renovatebot basebranch

renovate.json
=> renovate: scheduling to run every weekend

.github/CODEOWNERS, analytic/go.mod, analytic/go.sum, api/go.mod, api/go.sum, auth/config/app/config.go, auth/config/app/enums/messages.go, auth/go.mod, auth/go.sum, core/go.mod, core/go.sum, deployments/compose/compose-dev.yaml, deployments/compose/compose.yaml, messages/go.mod, messages/go.sum, vulnerability/go.mod, vulnerability/go.sum, webhook/go.mod, webhook/go.sum
Signed-off-by: wiliansilvazup wilian.silva@zup.com.br
Warn usage default content, may cause security warnings
- Adding warn when create default user in auth
- Adding warn when create default application admin in auth
- Comentaries in compose-dev and compose
=> CHORE: Warn: Add warn in all services to not usage default content

.semver.yaml, deployments/compose/compose.yaml, deployments/helm/horusec-platform/README.md, deployments/helm/horusec-platform/values.yaml, manager/deployments/helm/horusec-manager/values.yaml, manager/package-lock.json, manager/package.json
Signed-off-by: wilian <wilian.silva@zup.com.br>
=> Update versioning files

.github/workflows/dco.yaml
Update DCO validator to fix checks for PRs
=> actions: update DCO to recommended configurations

.github/workflows/new-release.yml
Add GH token with permission to sign commits. Update release branch creations
=> ci: add GH token with sign permissions

deployments/compose/compose-dev.yaml, deployments/compose/compose.yaml
Signed-off-by: nathanmartinszup <nathan.martins@zup.com.br>
=> Added missing HORUSEC_AUTH_URL env variable

deployments/compose/compose-dev.yaml, deployments/compose/compose.yaml
Signed-off-by: nathanmartinszup <nathan.martins@zup.com.br>
=> Added missing env var horusec manager url

e2e/cypress/package-lock.json, e2e/cypress/package.json, manager/package.json, manager/yarn.lock
e2e:bugfix - downgrade cypress version
Signed-off-by: lucas.bruno <lucas.bruno@zup.com.br>
=> e2e:bugfix - downgrade cypress version

.github/workflows/analytic-pipeline.yml, .github/workflows/api-pipeline.yml, .github/workflows/auth-pipeline.yml, .github/workflows/core-pipeline.yml, .github/workflows/e2e-pipeline.yml, .github/workflows/license.yaml, .github/workflows/manager-pipeline.yml, .github/workflows/messages-pipeline.yml, .github/workflows/migrations-pipeline.yml, .github/workflows/vulnerability-pipeline.yml, .github/workflows/webhook-pipeline.yml
Signed-off-by: Ian Cardoso <ian.cardoso@zup.com.br>
Fix bug found on #453 
=> pipelines:bugfix - now it runs when a PR or push is sent to main

.github/workflows/analytic-pipeline.yml, .github/workflows/api-pipeline.yml, .github/workflows/auth-pipeline.yml, .github/workflows/core-pipeline.yml, .github/workflows/manager-pipeline.yml, .github/workflows/messages-pipeline.yml, .github/workflows/migrations-pipeline.yml, .github/workflows/vulnerability-pipeline.yml, .github/workflows/webhook-pipeline.yml
Signed-off-by: Nathan Martins <nathan.martins@zup.com.br>
=> workflow/security:chore - updating security workflow to use latest rc

manager/src/App.tsx, manager/src/contexts/Auth/index.tsx, manager/src/contexts/Auth/keycloak.ts, manager/src/helpers/localStorage/currentPage.ts, manager/src/pages/Auth/Horusec/Login/index.tsx, manager/src/pages/Auth/Keycloak/index.tsx, manager/src/pages/Overview/index.tsx
manager:feature - During navigation on manager, save the
URL path for what the logout because token expiries, and
retry login, return on this saved path.
Signed-off-by: lucas.bruno <lucas.bruno@zup.com.br>
=> manager:feature - Return saved page after token expires.

.semver.yaml, deployments/compose/compose.yaml, deployments/helm/horusec-platform/README.md, deployments/helm/horusec-platform/values.yaml, manager/deployments/helm/horusec-manager/values.yaml, manager/package-lock.json, manager/package.json
Updating platform verions in all files to avoid some issues with the
release file.
Signed-off-by: Nathan Martins <nathan.martins@zup.com.br>
=> version:bugfix - updating platform version

auth/config/app/config.go, auth/config/app/config_test.go
Signed-off-by: Nathan Martins <nathan.martins@zup.com.br>
=> auth:bugfix - removing unnecessary log of duplicate user

deployments/compose/keycloak/compose-dev.yaml, deployments/compose/keycloak/compose.yaml, deployments/compose/keycloak/database/init.sql
Signed-off-by: Wilian Gabriel <wilian.silva@zup.com.br>
=> compose:feat - Adding compose of the keycloak file

core/internal/repositories/repository/repository.go
Signed-off-by: Wilian Gabriel <wilian.silva@zup.com.br>
=> core:hotfix - Add validation in repositories when not exist pagination

.github/workflows/release-beta.yml, .github/workflows/release-rc.yml, .goreleaser.yml
In this commit we found the problem in beta and rc,
because there is a flag to skip publish and this is wrong.
Signed-off-by: Wilian Gabriel <wilian.silva@zup.com.br>
=> release:hotfix - Fixing release process

deployments/compose/compose.yaml, deployments/helm/horusec-platform/README.md, deployments/helm/horusec-platform/values.yaml, manager/deployments/helm/horusec-manager/values.yaml, manager/package.json
This is a automatic pull request that contains changes to files that need to be updated with the new release version. Where the commit 83df8fa1fe528e8d0350e74e37c90c83276550c1 was cherry picked from the release branch, which already contains all the necessary changes.
=> versioning:release - [skip ci] automatic pull request updating versioning files
